# Docker Compose 配置文件
# 用于简化 Docker 镜像的构建和运行
version: '3.8'

services:
  # 基础镜像构建服务
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: crawl4ai-base:latest
    # 基础镜像不需要运行，只用于构建
    command: /bin/true

  # 应用镜像构建和运行服务
  crawl4ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: crawl4ai-app:latest
    # 端口映射：将容器的 7861 端口映射到宿主机的 7861 端口
    ports:
      - "7861:7861"
    # 挂载输出目录到宿主机，方便查看结果
    volumes:
      - ./output:/app/output
      - ./crawl_links.db:/app/crawl_links.db
      - ./crawler_logs.txt:/app/crawler_logs.txt
    # 如果需要传递环境变量，可以在这里配置
    environment:
      - PYTHONUNBUFFERED=1
    # 如果需要网络访问，可以配置网络模式
    # network_mode: "host"
    depends_on:
      - base